// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: networking.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Phorkus.Proto {

  /// <summary>Holder for reflection information generated from networking.proto</summary>
  public static partial class NetworkingReflection {

    #region Descriptor
    /// <summary>File descriptor for networking.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NetworkingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBuZXR3b3JraW5nLnByb3RvGg1kZWZhdWx0LnByb3RvGhF0cmFuc2FjdGlv",
            "bi5wcm90bxoLYmxvY2sucHJvdG8aCm5vZGUucHJvdG8aD2NvbnNlbnN1cy5w",
            "cm90byInChBIYW5kc2hha2VSZXF1ZXN0EhMKBG5vZGUYASABKAsyBS5Ob2Rl",
            "IiUKDkhhbmRzaGFrZVJlcGx5EhMKBG5vZGUYASABKAsyBS5Ob2RlIjYKC1Bp",
            "bmdSZXF1ZXN0EhEKCXRpbWVzdGFtcBgBIAEoBBIUCgxibG9ja19oZWlnaHQY",
            "AiABKAQiNAoJUGluZ1JlcGx5EhEKCXRpbWVzdGFtcBgBIAEoBBIUCgxibG9j",
            "a19oZWlnaHQYAiABKAQiOgoYR2V0QmxvY2tzQnlIYXNoZXNSZXF1ZXN0Eh4K",
            "DGJsb2NrX2hhc2hlcxgBIAMoCzIILlVJbnQyNTYiMAoWR2V0QmxvY2tzQnlI",
            "YXNoZXNSZXBseRIWCgZibG9ja3MYASADKAsyBi5CbG9jayJHCh1HZXRCbG9j",
            "a3NCeUhlaWdodFJhbmdlUmVxdWVzdBITCgtmcm9tX2hlaWdodBgBIAEoBBIR",
            "Cgl0b19oZWlnaHQYAiABKAQiPQobR2V0QmxvY2tzQnlIZWlnaHRSYW5nZVJl",
            "cGx5Eh4KDGJsb2NrX2hhc2hlcxgBIAMoCzIILlVJbnQyNTYiRgoeR2V0VHJh",
            "bnNhY3Rpb25zQnlIYXNoZXNSZXF1ZXN0EiQKEnRyYW5zYWN0aW9uX2hhc2hl",
            "cxgBIAMoCzIILlVJbnQyNTYiSAocR2V0VHJhbnNhY3Rpb25zQnlIYXNoZXNS",
            "ZXBseRIoCgx0cmFuc2FjdGlvbnMYASADKAsyEi5TaWduZWRUcmFuc2FjdGlv",
            "biIjChBUaHJlc2hvbGRSZXF1ZXN0Eg8KB21lc3NhZ2UYASABKAwiugEKEENv",
            "bnNlbnN1c01lc3NhZ2USMQoTY2hhbmdlX3ZpZXdfcmVxdWVzdBgBIAEoCzIS",
            "LkNoYW5nZVZpZXdSZXF1ZXN0SAASNQoVYmxvY2tfcHJlcGFyZV9yZXF1ZXN0",
            "GAIgASgLMhQuQmxvY2tQcmVwYXJlUmVxdWVzdEgAEjEKE2Jsb2NrX3ByZXBh",
            "cmVfcmVwbHkYAyABKAsyEi5CbG9ja1ByZXBhcmVSZXBseUgAQgkKB3BheWxv",
            "YWQigQYKDk5ldHdvcmtNZXNzYWdlEg0KBW1hZ2ljGAEgASgNEi4KEWhhbmRz",
            "aGFrZV9yZXF1ZXN0GAogASgLMhEuSGFuZHNoYWtlUmVxdWVzdEgAEioKD2hh",
            "bmRzaGFrZV9yZXBseRgLIAEoCzIPLkhhbmRzaGFrZVJlcGx5SAASJAoMcGlu",
            "Z19yZXF1ZXN0GAwgASgLMgwuUGluZ1JlcXVlc3RIABIgCgpwaW5nX3JlcGx5",
            "GA0gASgLMgouUGluZ1JlcGx5SAASQQocZ2V0X2Jsb2Nrc19ieV9oYXNoZXNf",
            "cmVxdWVzdBgOIAEoCzIZLkdldEJsb2Nrc0J5SGFzaGVzUmVxdWVzdEgAEj0K",
            "GmdldF9ibG9ja3NfYnlfaGFzaGVzX3JlcGx5GA8gASgLMhcuR2V0QmxvY2tz",
            "QnlIYXNoZXNSZXBseUgAEkwKImdldF9ibG9ja3NfYnlfaGVpZ2h0X3Jhbmdl",
            "X3JlcXVlc3QYECABKAsyHi5HZXRCbG9ja3NCeUhlaWdodFJhbmdlUmVxdWVz",
            "dEgAEkgKIGdldF9ibG9ja3NfYnlfaGVpZ2h0X3JhbmdlX3JlcGx5GBEgASgL",
            "MhwuR2V0QmxvY2tzQnlIZWlnaHRSYW5nZVJlcGx5SAASTQoiZ2V0X3RyYW5z",
            "YWN0aW9uc19ieV9oYXNoZXNfcmVxdWVzdBgSIAEoCzIfLkdldFRyYW5zYWN0",
            "aW9uc0J5SGFzaGVzUmVxdWVzdEgAEkkKIGdldF90cmFuc2FjdGlvbnNfYnlf",
            "aGFzaGVzX3JlcGx5GBMgASgLMh0uR2V0VHJhbnNhY3Rpb25zQnlIYXNoZXNS",
            "ZXBseUgAEi4KEXRocmVzaG9sZF9yZXF1ZXN0GBQgASgLMhEuVGhyZXNob2xk",
            "UmVxdWVzdEgAEi4KEWNvbnNlbnN1c19tZXNzYWdlGBUgASgLMhEuQ29uc2Vu",
            "c3VzTWVzc2FnZUgAEh0KCXNpZ25hdHVyZRhkIAEoCzIKLlNpZ25hdHVyZUIJ",
            "CgdtZXNzYWdlQhCqAg1QaG9ya3VzLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Phorkus.Proto.DefaultReflection.Descriptor, global::Phorkus.Proto.TransactionReflection.Descriptor, global::Phorkus.Proto.BlockReflection.Descriptor, global::Phorkus.Proto.NodeReflection.Descriptor, global::Phorkus.Proto.ConsensusReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Phorkus.Proto.HandshakeRequest), global::Phorkus.Proto.HandshakeRequest.Parser, new[]{ "Node" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Phorkus.Proto.HandshakeReply), global::Phorkus.Proto.HandshakeReply.Parser, new[]{ "Node" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Phorkus.Proto.PingRequest), global::Phorkus.Proto.PingRequest.Parser, new[]{ "Timestamp", "BlockHeight" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Phorkus.Proto.PingReply), global::Phorkus.Proto.PingReply.Parser, new[]{ "Timestamp", "BlockHeight" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Phorkus.Proto.GetBlocksByHashesRequest), global::Phorkus.Proto.GetBlocksByHashesRequest.Parser, new[]{ "BlockHashes" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Phorkus.Proto.GetBlocksByHashesReply), global::Phorkus.Proto.GetBlocksByHashesReply.Parser, new[]{ "Blocks" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Phorkus.Proto.GetBlocksByHeightRangeRequest), global::Phorkus.Proto.GetBlocksByHeightRangeRequest.Parser, new[]{ "FromHeight", "ToHeight" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Phorkus.Proto.GetBlocksByHeightRangeReply), global::Phorkus.Proto.GetBlocksByHeightRangeReply.Parser, new[]{ "BlockHashes" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Phorkus.Proto.GetTransactionsByHashesRequest), global::Phorkus.Proto.GetTransactionsByHashesRequest.Parser, new[]{ "TransactionHashes" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Phorkus.Proto.GetTransactionsByHashesReply), global::Phorkus.Proto.GetTransactionsByHashesReply.Parser, new[]{ "Transactions" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Phorkus.Proto.ThresholdRequest), global::Phorkus.Proto.ThresholdRequest.Parser, new[]{ "Message" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Phorkus.Proto.ConsensusMessage), global::Phorkus.Proto.ConsensusMessage.Parser, new[]{ "ChangeViewRequest", "BlockPrepareRequest", "BlockPrepareReply" }, new[]{ "Payload" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Phorkus.Proto.NetworkMessage), global::Phorkus.Proto.NetworkMessage.Parser, new[]{ "Magic", "HandshakeRequest", "HandshakeReply", "PingRequest", "PingReply", "GetBlocksByHashesRequest", "GetBlocksByHashesReply", "GetBlocksByHeightRangeRequest", "GetBlocksByHeightRangeReply", "GetTransactionsByHashesRequest", "GetTransactionsByHashesReply", "ThresholdRequest", "ConsensusMessage", "Signature" }, new[]{ "Message" }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class HandshakeRequest : pb::IMessage<HandshakeRequest> {
    private static readonly pb::MessageParser<HandshakeRequest> _parser = new pb::MessageParser<HandshakeRequest>(() => new HandshakeRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HandshakeRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phorkus.Proto.NetworkingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HandshakeRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HandshakeRequest(HandshakeRequest other) : this() {
      node_ = other.node_ != null ? other.node_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HandshakeRequest Clone() {
      return new HandshakeRequest(this);
    }

    /// <summary>Field number for the "node" field.</summary>
    public const int NodeFieldNumber = 1;
    private global::Phorkus.Proto.Node node_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.Node Node {
      get { return node_; }
      set {
        node_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HandshakeRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HandshakeRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Node, other.Node)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (node_ != null) hash ^= Node.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (node_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Node);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (node_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Node);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HandshakeRequest other) {
      if (other == null) {
        return;
      }
      if (other.node_ != null) {
        if (node_ == null) {
          node_ = new global::Phorkus.Proto.Node();
        }
        Node.MergeFrom(other.Node);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (node_ == null) {
              node_ = new global::Phorkus.Proto.Node();
            }
            input.ReadMessage(node_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class HandshakeReply : pb::IMessage<HandshakeReply> {
    private static readonly pb::MessageParser<HandshakeReply> _parser = new pb::MessageParser<HandshakeReply>(() => new HandshakeReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HandshakeReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phorkus.Proto.NetworkingReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HandshakeReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HandshakeReply(HandshakeReply other) : this() {
      node_ = other.node_ != null ? other.node_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HandshakeReply Clone() {
      return new HandshakeReply(this);
    }

    /// <summary>Field number for the "node" field.</summary>
    public const int NodeFieldNumber = 1;
    private global::Phorkus.Proto.Node node_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.Node Node {
      get { return node_; }
      set {
        node_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HandshakeReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HandshakeReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Node, other.Node)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (node_ != null) hash ^= Node.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (node_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Node);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (node_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Node);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HandshakeReply other) {
      if (other == null) {
        return;
      }
      if (other.node_ != null) {
        if (node_ == null) {
          node_ = new global::Phorkus.Proto.Node();
        }
        Node.MergeFrom(other.Node);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (node_ == null) {
              node_ = new global::Phorkus.Proto.Node();
            }
            input.ReadMessage(node_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PingRequest : pb::IMessage<PingRequest> {
    private static readonly pb::MessageParser<PingRequest> _parser = new pb::MessageParser<PingRequest>(() => new PingRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PingRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phorkus.Proto.NetworkingReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PingRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PingRequest(PingRequest other) : this() {
      timestamp_ = other.timestamp_;
      blockHeight_ = other.blockHeight_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PingRequest Clone() {
      return new PingRequest(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private ulong timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "block_height" field.</summary>
    public const int BlockHeightFieldNumber = 2;
    private ulong blockHeight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong BlockHeight {
      get { return blockHeight_; }
      set {
        blockHeight_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PingRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PingRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      if (BlockHeight != other.BlockHeight) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0UL) hash ^= Timestamp.GetHashCode();
      if (BlockHeight != 0UL) hash ^= BlockHeight.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Timestamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Timestamp);
      }
      if (BlockHeight != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(BlockHeight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
      }
      if (BlockHeight != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(BlockHeight);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PingRequest other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0UL) {
        Timestamp = other.Timestamp;
      }
      if (other.BlockHeight != 0UL) {
        BlockHeight = other.BlockHeight;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 16: {
            BlockHeight = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PingReply : pb::IMessage<PingReply> {
    private static readonly pb::MessageParser<PingReply> _parser = new pb::MessageParser<PingReply>(() => new PingReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PingReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phorkus.Proto.NetworkingReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PingReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PingReply(PingReply other) : this() {
      timestamp_ = other.timestamp_;
      blockHeight_ = other.blockHeight_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PingReply Clone() {
      return new PingReply(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private ulong timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "block_height" field.</summary>
    public const int BlockHeightFieldNumber = 2;
    private ulong blockHeight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong BlockHeight {
      get { return blockHeight_; }
      set {
        blockHeight_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PingReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PingReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      if (BlockHeight != other.BlockHeight) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0UL) hash ^= Timestamp.GetHashCode();
      if (BlockHeight != 0UL) hash ^= BlockHeight.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Timestamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Timestamp);
      }
      if (BlockHeight != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(BlockHeight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
      }
      if (BlockHeight != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(BlockHeight);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PingReply other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0UL) {
        Timestamp = other.Timestamp;
      }
      if (other.BlockHeight != 0UL) {
        BlockHeight = other.BlockHeight;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 16: {
            BlockHeight = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetBlocksByHashesRequest : pb::IMessage<GetBlocksByHashesRequest> {
    private static readonly pb::MessageParser<GetBlocksByHashesRequest> _parser = new pb::MessageParser<GetBlocksByHashesRequest>(() => new GetBlocksByHashesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetBlocksByHashesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phorkus.Proto.NetworkingReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetBlocksByHashesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetBlocksByHashesRequest(GetBlocksByHashesRequest other) : this() {
      blockHashes_ = other.blockHashes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetBlocksByHashesRequest Clone() {
      return new GetBlocksByHashesRequest(this);
    }

    /// <summary>Field number for the "block_hashes" field.</summary>
    public const int BlockHashesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Phorkus.Proto.UInt256> _repeated_blockHashes_codec
        = pb::FieldCodec.ForMessage(10, global::Phorkus.Proto.UInt256.Parser);
    private readonly pbc::RepeatedField<global::Phorkus.Proto.UInt256> blockHashes_ = new pbc::RepeatedField<global::Phorkus.Proto.UInt256>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Phorkus.Proto.UInt256> BlockHashes {
      get { return blockHashes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetBlocksByHashesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetBlocksByHashesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!blockHashes_.Equals(other.blockHashes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= blockHashes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      blockHashes_.WriteTo(output, _repeated_blockHashes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += blockHashes_.CalculateSize(_repeated_blockHashes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetBlocksByHashesRequest other) {
      if (other == null) {
        return;
      }
      blockHashes_.Add(other.blockHashes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            blockHashes_.AddEntriesFrom(input, _repeated_blockHashes_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetBlocksByHashesReply : pb::IMessage<GetBlocksByHashesReply> {
    private static readonly pb::MessageParser<GetBlocksByHashesReply> _parser = new pb::MessageParser<GetBlocksByHashesReply>(() => new GetBlocksByHashesReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetBlocksByHashesReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phorkus.Proto.NetworkingReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetBlocksByHashesReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetBlocksByHashesReply(GetBlocksByHashesReply other) : this() {
      blocks_ = other.blocks_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetBlocksByHashesReply Clone() {
      return new GetBlocksByHashesReply(this);
    }

    /// <summary>Field number for the "blocks" field.</summary>
    public const int BlocksFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Phorkus.Proto.Block> _repeated_blocks_codec
        = pb::FieldCodec.ForMessage(10, global::Phorkus.Proto.Block.Parser);
    private readonly pbc::RepeatedField<global::Phorkus.Proto.Block> blocks_ = new pbc::RepeatedField<global::Phorkus.Proto.Block>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Phorkus.Proto.Block> Blocks {
      get { return blocks_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetBlocksByHashesReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetBlocksByHashesReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!blocks_.Equals(other.blocks_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= blocks_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      blocks_.WriteTo(output, _repeated_blocks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += blocks_.CalculateSize(_repeated_blocks_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetBlocksByHashesReply other) {
      if (other == null) {
        return;
      }
      blocks_.Add(other.blocks_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            blocks_.AddEntriesFrom(input, _repeated_blocks_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetBlocksByHeightRangeRequest : pb::IMessage<GetBlocksByHeightRangeRequest> {
    private static readonly pb::MessageParser<GetBlocksByHeightRangeRequest> _parser = new pb::MessageParser<GetBlocksByHeightRangeRequest>(() => new GetBlocksByHeightRangeRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetBlocksByHeightRangeRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phorkus.Proto.NetworkingReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetBlocksByHeightRangeRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetBlocksByHeightRangeRequest(GetBlocksByHeightRangeRequest other) : this() {
      fromHeight_ = other.fromHeight_;
      toHeight_ = other.toHeight_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetBlocksByHeightRangeRequest Clone() {
      return new GetBlocksByHeightRangeRequest(this);
    }

    /// <summary>Field number for the "from_height" field.</summary>
    public const int FromHeightFieldNumber = 1;
    private ulong fromHeight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong FromHeight {
      get { return fromHeight_; }
      set {
        fromHeight_ = value;
      }
    }

    /// <summary>Field number for the "to_height" field.</summary>
    public const int ToHeightFieldNumber = 2;
    private ulong toHeight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong ToHeight {
      get { return toHeight_; }
      set {
        toHeight_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetBlocksByHeightRangeRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetBlocksByHeightRangeRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FromHeight != other.FromHeight) return false;
      if (ToHeight != other.ToHeight) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FromHeight != 0UL) hash ^= FromHeight.GetHashCode();
      if (ToHeight != 0UL) hash ^= ToHeight.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (FromHeight != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(FromHeight);
      }
      if (ToHeight != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(ToHeight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FromHeight != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(FromHeight);
      }
      if (ToHeight != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ToHeight);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetBlocksByHeightRangeRequest other) {
      if (other == null) {
        return;
      }
      if (other.FromHeight != 0UL) {
        FromHeight = other.FromHeight;
      }
      if (other.ToHeight != 0UL) {
        ToHeight = other.ToHeight;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FromHeight = input.ReadUInt64();
            break;
          }
          case 16: {
            ToHeight = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetBlocksByHeightRangeReply : pb::IMessage<GetBlocksByHeightRangeReply> {
    private static readonly pb::MessageParser<GetBlocksByHeightRangeReply> _parser = new pb::MessageParser<GetBlocksByHeightRangeReply>(() => new GetBlocksByHeightRangeReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetBlocksByHeightRangeReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phorkus.Proto.NetworkingReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetBlocksByHeightRangeReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetBlocksByHeightRangeReply(GetBlocksByHeightRangeReply other) : this() {
      blockHashes_ = other.blockHashes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetBlocksByHeightRangeReply Clone() {
      return new GetBlocksByHeightRangeReply(this);
    }

    /// <summary>Field number for the "block_hashes" field.</summary>
    public const int BlockHashesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Phorkus.Proto.UInt256> _repeated_blockHashes_codec
        = pb::FieldCodec.ForMessage(10, global::Phorkus.Proto.UInt256.Parser);
    private readonly pbc::RepeatedField<global::Phorkus.Proto.UInt256> blockHashes_ = new pbc::RepeatedField<global::Phorkus.Proto.UInt256>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Phorkus.Proto.UInt256> BlockHashes {
      get { return blockHashes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetBlocksByHeightRangeReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetBlocksByHeightRangeReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!blockHashes_.Equals(other.blockHashes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= blockHashes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      blockHashes_.WriteTo(output, _repeated_blockHashes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += blockHashes_.CalculateSize(_repeated_blockHashes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetBlocksByHeightRangeReply other) {
      if (other == null) {
        return;
      }
      blockHashes_.Add(other.blockHashes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            blockHashes_.AddEntriesFrom(input, _repeated_blockHashes_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetTransactionsByHashesRequest : pb::IMessage<GetTransactionsByHashesRequest> {
    private static readonly pb::MessageParser<GetTransactionsByHashesRequest> _parser = new pb::MessageParser<GetTransactionsByHashesRequest>(() => new GetTransactionsByHashesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetTransactionsByHashesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phorkus.Proto.NetworkingReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetTransactionsByHashesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetTransactionsByHashesRequest(GetTransactionsByHashesRequest other) : this() {
      transactionHashes_ = other.transactionHashes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetTransactionsByHashesRequest Clone() {
      return new GetTransactionsByHashesRequest(this);
    }

    /// <summary>Field number for the "transaction_hashes" field.</summary>
    public const int TransactionHashesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Phorkus.Proto.UInt256> _repeated_transactionHashes_codec
        = pb::FieldCodec.ForMessage(10, global::Phorkus.Proto.UInt256.Parser);
    private readonly pbc::RepeatedField<global::Phorkus.Proto.UInt256> transactionHashes_ = new pbc::RepeatedField<global::Phorkus.Proto.UInt256>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Phorkus.Proto.UInt256> TransactionHashes {
      get { return transactionHashes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetTransactionsByHashesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetTransactionsByHashesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!transactionHashes_.Equals(other.transactionHashes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= transactionHashes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      transactionHashes_.WriteTo(output, _repeated_transactionHashes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += transactionHashes_.CalculateSize(_repeated_transactionHashes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetTransactionsByHashesRequest other) {
      if (other == null) {
        return;
      }
      transactionHashes_.Add(other.transactionHashes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            transactionHashes_.AddEntriesFrom(input, _repeated_transactionHashes_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetTransactionsByHashesReply : pb::IMessage<GetTransactionsByHashesReply> {
    private static readonly pb::MessageParser<GetTransactionsByHashesReply> _parser = new pb::MessageParser<GetTransactionsByHashesReply>(() => new GetTransactionsByHashesReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetTransactionsByHashesReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phorkus.Proto.NetworkingReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetTransactionsByHashesReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetTransactionsByHashesReply(GetTransactionsByHashesReply other) : this() {
      transactions_ = other.transactions_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetTransactionsByHashesReply Clone() {
      return new GetTransactionsByHashesReply(this);
    }

    /// <summary>Field number for the "transactions" field.</summary>
    public const int TransactionsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Phorkus.Proto.SignedTransaction> _repeated_transactions_codec
        = pb::FieldCodec.ForMessage(10, global::Phorkus.Proto.SignedTransaction.Parser);
    private readonly pbc::RepeatedField<global::Phorkus.Proto.SignedTransaction> transactions_ = new pbc::RepeatedField<global::Phorkus.Proto.SignedTransaction>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Phorkus.Proto.SignedTransaction> Transactions {
      get { return transactions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetTransactionsByHashesReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetTransactionsByHashesReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!transactions_.Equals(other.transactions_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= transactions_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      transactions_.WriteTo(output, _repeated_transactions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += transactions_.CalculateSize(_repeated_transactions_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetTransactionsByHashesReply other) {
      if (other == null) {
        return;
      }
      transactions_.Add(other.transactions_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            transactions_.AddEntriesFrom(input, _repeated_transactions_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ThresholdRequest : pb::IMessage<ThresholdRequest> {
    private static readonly pb::MessageParser<ThresholdRequest> _parser = new pb::MessageParser<ThresholdRequest>(() => new ThresholdRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ThresholdRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phorkus.Proto.NetworkingReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ThresholdRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ThresholdRequest(ThresholdRequest other) : this() {
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ThresholdRequest Clone() {
      return new ThresholdRequest(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private pb::ByteString message_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ThresholdRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ThresholdRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ThresholdRequest other) {
      if (other == null) {
        return;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Message = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ConsensusMessage : pb::IMessage<ConsensusMessage> {
    private static readonly pb::MessageParser<ConsensusMessage> _parser = new pb::MessageParser<ConsensusMessage>(() => new ConsensusMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConsensusMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phorkus.Proto.NetworkingReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConsensusMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConsensusMessage(ConsensusMessage other) : this() {
      switch (other.PayloadCase) {
        case PayloadOneofCase.ChangeViewRequest:
          ChangeViewRequest = other.ChangeViewRequest.Clone();
          break;
        case PayloadOneofCase.BlockPrepareRequest:
          BlockPrepareRequest = other.BlockPrepareRequest.Clone();
          break;
        case PayloadOneofCase.BlockPrepareReply:
          BlockPrepareReply = other.BlockPrepareReply.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConsensusMessage Clone() {
      return new ConsensusMessage(this);
    }

    /// <summary>Field number for the "change_view_request" field.</summary>
    public const int ChangeViewRequestFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.ChangeViewRequest ChangeViewRequest {
      get { return payloadCase_ == PayloadOneofCase.ChangeViewRequest ? (global::Phorkus.Proto.ChangeViewRequest) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ChangeViewRequest;
      }
    }

    /// <summary>Field number for the "block_prepare_request" field.</summary>
    public const int BlockPrepareRequestFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.BlockPrepareRequest BlockPrepareRequest {
      get { return payloadCase_ == PayloadOneofCase.BlockPrepareRequest ? (global::Phorkus.Proto.BlockPrepareRequest) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.BlockPrepareRequest;
      }
    }

    /// <summary>Field number for the "block_prepare_reply" field.</summary>
    public const int BlockPrepareReplyFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.BlockPrepareReply BlockPrepareReply {
      get { return payloadCase_ == PayloadOneofCase.BlockPrepareReply ? (global::Phorkus.Proto.BlockPrepareReply) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.BlockPrepareReply;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      ChangeViewRequest = 1,
      BlockPrepareRequest = 2,
      BlockPrepareReply = 3,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConsensusMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConsensusMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ChangeViewRequest, other.ChangeViewRequest)) return false;
      if (!object.Equals(BlockPrepareRequest, other.BlockPrepareRequest)) return false;
      if (!object.Equals(BlockPrepareReply, other.BlockPrepareReply)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (payloadCase_ == PayloadOneofCase.ChangeViewRequest) hash ^= ChangeViewRequest.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.BlockPrepareRequest) hash ^= BlockPrepareRequest.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.BlockPrepareReply) hash ^= BlockPrepareReply.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (payloadCase_ == PayloadOneofCase.ChangeViewRequest) {
        output.WriteRawTag(10);
        output.WriteMessage(ChangeViewRequest);
      }
      if (payloadCase_ == PayloadOneofCase.BlockPrepareRequest) {
        output.WriteRawTag(18);
        output.WriteMessage(BlockPrepareRequest);
      }
      if (payloadCase_ == PayloadOneofCase.BlockPrepareReply) {
        output.WriteRawTag(26);
        output.WriteMessage(BlockPrepareReply);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (payloadCase_ == PayloadOneofCase.ChangeViewRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangeViewRequest);
      }
      if (payloadCase_ == PayloadOneofCase.BlockPrepareRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BlockPrepareRequest);
      }
      if (payloadCase_ == PayloadOneofCase.BlockPrepareReply) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BlockPrepareReply);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConsensusMessage other) {
      if (other == null) {
        return;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.ChangeViewRequest:
          if (ChangeViewRequest == null) {
            ChangeViewRequest = new global::Phorkus.Proto.ChangeViewRequest();
          }
          ChangeViewRequest.MergeFrom(other.ChangeViewRequest);
          break;
        case PayloadOneofCase.BlockPrepareRequest:
          if (BlockPrepareRequest == null) {
            BlockPrepareRequest = new global::Phorkus.Proto.BlockPrepareRequest();
          }
          BlockPrepareRequest.MergeFrom(other.BlockPrepareRequest);
          break;
        case PayloadOneofCase.BlockPrepareReply:
          if (BlockPrepareReply == null) {
            BlockPrepareReply = new global::Phorkus.Proto.BlockPrepareReply();
          }
          BlockPrepareReply.MergeFrom(other.BlockPrepareReply);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Phorkus.Proto.ChangeViewRequest subBuilder = new global::Phorkus.Proto.ChangeViewRequest();
            if (payloadCase_ == PayloadOneofCase.ChangeViewRequest) {
              subBuilder.MergeFrom(ChangeViewRequest);
            }
            input.ReadMessage(subBuilder);
            ChangeViewRequest = subBuilder;
            break;
          }
          case 18: {
            global::Phorkus.Proto.BlockPrepareRequest subBuilder = new global::Phorkus.Proto.BlockPrepareRequest();
            if (payloadCase_ == PayloadOneofCase.BlockPrepareRequest) {
              subBuilder.MergeFrom(BlockPrepareRequest);
            }
            input.ReadMessage(subBuilder);
            BlockPrepareRequest = subBuilder;
            break;
          }
          case 26: {
            global::Phorkus.Proto.BlockPrepareReply subBuilder = new global::Phorkus.Proto.BlockPrepareReply();
            if (payloadCase_ == PayloadOneofCase.BlockPrepareReply) {
              subBuilder.MergeFrom(BlockPrepareReply);
            }
            input.ReadMessage(subBuilder);
            BlockPrepareReply = subBuilder;
            break;
          }
        }
      }
    }

  }

  public sealed partial class NetworkMessage : pb::IMessage<NetworkMessage> {
    private static readonly pb::MessageParser<NetworkMessage> _parser = new pb::MessageParser<NetworkMessage>(() => new NetworkMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NetworkMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Phorkus.Proto.NetworkingReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetworkMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetworkMessage(NetworkMessage other) : this() {
      magic_ = other.magic_;
      signature_ = other.signature_ != null ? other.signature_.Clone() : null;
      switch (other.MessageCase) {
        case MessageOneofCase.HandshakeRequest:
          HandshakeRequest = other.HandshakeRequest.Clone();
          break;
        case MessageOneofCase.HandshakeReply:
          HandshakeReply = other.HandshakeReply.Clone();
          break;
        case MessageOneofCase.PingRequest:
          PingRequest = other.PingRequest.Clone();
          break;
        case MessageOneofCase.PingReply:
          PingReply = other.PingReply.Clone();
          break;
        case MessageOneofCase.GetBlocksByHashesRequest:
          GetBlocksByHashesRequest = other.GetBlocksByHashesRequest.Clone();
          break;
        case MessageOneofCase.GetBlocksByHashesReply:
          GetBlocksByHashesReply = other.GetBlocksByHashesReply.Clone();
          break;
        case MessageOneofCase.GetBlocksByHeightRangeRequest:
          GetBlocksByHeightRangeRequest = other.GetBlocksByHeightRangeRequest.Clone();
          break;
        case MessageOneofCase.GetBlocksByHeightRangeReply:
          GetBlocksByHeightRangeReply = other.GetBlocksByHeightRangeReply.Clone();
          break;
        case MessageOneofCase.GetTransactionsByHashesRequest:
          GetTransactionsByHashesRequest = other.GetTransactionsByHashesRequest.Clone();
          break;
        case MessageOneofCase.GetTransactionsByHashesReply:
          GetTransactionsByHashesReply = other.GetTransactionsByHashesReply.Clone();
          break;
        case MessageOneofCase.ThresholdRequest:
          ThresholdRequest = other.ThresholdRequest.Clone();
          break;
        case MessageOneofCase.ConsensusMessage:
          ConsensusMessage = other.ConsensusMessage.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetworkMessage Clone() {
      return new NetworkMessage(this);
    }

    /// <summary>Field number for the "magic" field.</summary>
    public const int MagicFieldNumber = 1;
    private uint magic_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Magic {
      get { return magic_; }
      set {
        magic_ = value;
      }
    }

    /// <summary>Field number for the "handshake_request" field.</summary>
    public const int HandshakeRequestFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.HandshakeRequest HandshakeRequest {
      get { return messageCase_ == MessageOneofCase.HandshakeRequest ? (global::Phorkus.Proto.HandshakeRequest) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.HandshakeRequest;
      }
    }

    /// <summary>Field number for the "handshake_reply" field.</summary>
    public const int HandshakeReplyFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.HandshakeReply HandshakeReply {
      get { return messageCase_ == MessageOneofCase.HandshakeReply ? (global::Phorkus.Proto.HandshakeReply) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.HandshakeReply;
      }
    }

    /// <summary>Field number for the "ping_request" field.</summary>
    public const int PingRequestFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.PingRequest PingRequest {
      get { return messageCase_ == MessageOneofCase.PingRequest ? (global::Phorkus.Proto.PingRequest) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.PingRequest;
      }
    }

    /// <summary>Field number for the "ping_reply" field.</summary>
    public const int PingReplyFieldNumber = 13;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.PingReply PingReply {
      get { return messageCase_ == MessageOneofCase.PingReply ? (global::Phorkus.Proto.PingReply) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.PingReply;
      }
    }

    /// <summary>Field number for the "get_blocks_by_hashes_request" field.</summary>
    public const int GetBlocksByHashesRequestFieldNumber = 14;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.GetBlocksByHashesRequest GetBlocksByHashesRequest {
      get { return messageCase_ == MessageOneofCase.GetBlocksByHashesRequest ? (global::Phorkus.Proto.GetBlocksByHashesRequest) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.GetBlocksByHashesRequest;
      }
    }

    /// <summary>Field number for the "get_blocks_by_hashes_reply" field.</summary>
    public const int GetBlocksByHashesReplyFieldNumber = 15;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.GetBlocksByHashesReply GetBlocksByHashesReply {
      get { return messageCase_ == MessageOneofCase.GetBlocksByHashesReply ? (global::Phorkus.Proto.GetBlocksByHashesReply) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.GetBlocksByHashesReply;
      }
    }

    /// <summary>Field number for the "get_blocks_by_height_range_request" field.</summary>
    public const int GetBlocksByHeightRangeRequestFieldNumber = 16;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.GetBlocksByHeightRangeRequest GetBlocksByHeightRangeRequest {
      get { return messageCase_ == MessageOneofCase.GetBlocksByHeightRangeRequest ? (global::Phorkus.Proto.GetBlocksByHeightRangeRequest) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.GetBlocksByHeightRangeRequest;
      }
    }

    /// <summary>Field number for the "get_blocks_by_height_range_reply" field.</summary>
    public const int GetBlocksByHeightRangeReplyFieldNumber = 17;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.GetBlocksByHeightRangeReply GetBlocksByHeightRangeReply {
      get { return messageCase_ == MessageOneofCase.GetBlocksByHeightRangeReply ? (global::Phorkus.Proto.GetBlocksByHeightRangeReply) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.GetBlocksByHeightRangeReply;
      }
    }

    /// <summary>Field number for the "get_transactions_by_hashes_request" field.</summary>
    public const int GetTransactionsByHashesRequestFieldNumber = 18;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.GetTransactionsByHashesRequest GetTransactionsByHashesRequest {
      get { return messageCase_ == MessageOneofCase.GetTransactionsByHashesRequest ? (global::Phorkus.Proto.GetTransactionsByHashesRequest) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.GetTransactionsByHashesRequest;
      }
    }

    /// <summary>Field number for the "get_transactions_by_hashes_reply" field.</summary>
    public const int GetTransactionsByHashesReplyFieldNumber = 19;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.GetTransactionsByHashesReply GetTransactionsByHashesReply {
      get { return messageCase_ == MessageOneofCase.GetTransactionsByHashesReply ? (global::Phorkus.Proto.GetTransactionsByHashesReply) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.GetTransactionsByHashesReply;
      }
    }

    /// <summary>Field number for the "threshold_request" field.</summary>
    public const int ThresholdRequestFieldNumber = 20;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.ThresholdRequest ThresholdRequest {
      get { return messageCase_ == MessageOneofCase.ThresholdRequest ? (global::Phorkus.Proto.ThresholdRequest) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.ThresholdRequest;
      }
    }

    /// <summary>Field number for the "consensus_message" field.</summary>
    public const int ConsensusMessageFieldNumber = 21;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.ConsensusMessage ConsensusMessage {
      get { return messageCase_ == MessageOneofCase.ConsensusMessage ? (global::Phorkus.Proto.ConsensusMessage) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.ConsensusMessage;
      }
    }

    /// <summary>Field number for the "signature" field.</summary>
    public const int SignatureFieldNumber = 100;
    private global::Phorkus.Proto.Signature signature_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Phorkus.Proto.Signature Signature {
      get { return signature_; }
      set {
        signature_ = value;
      }
    }

    private object message_;
    /// <summary>Enum of possible cases for the "message" oneof.</summary>
    public enum MessageOneofCase {
      None = 0,
      HandshakeRequest = 10,
      HandshakeReply = 11,
      PingRequest = 12,
      PingReply = 13,
      GetBlocksByHashesRequest = 14,
      GetBlocksByHashesReply = 15,
      GetBlocksByHeightRangeRequest = 16,
      GetBlocksByHeightRangeReply = 17,
      GetTransactionsByHashesRequest = 18,
      GetTransactionsByHashesReply = 19,
      ThresholdRequest = 20,
      ConsensusMessage = 21,
    }
    private MessageOneofCase messageCase_ = MessageOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageOneofCase MessageCase {
      get { return messageCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMessage() {
      messageCase_ = MessageOneofCase.None;
      message_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NetworkMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NetworkMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Magic != other.Magic) return false;
      if (!object.Equals(HandshakeRequest, other.HandshakeRequest)) return false;
      if (!object.Equals(HandshakeReply, other.HandshakeReply)) return false;
      if (!object.Equals(PingRequest, other.PingRequest)) return false;
      if (!object.Equals(PingReply, other.PingReply)) return false;
      if (!object.Equals(GetBlocksByHashesRequest, other.GetBlocksByHashesRequest)) return false;
      if (!object.Equals(GetBlocksByHashesReply, other.GetBlocksByHashesReply)) return false;
      if (!object.Equals(GetBlocksByHeightRangeRequest, other.GetBlocksByHeightRangeRequest)) return false;
      if (!object.Equals(GetBlocksByHeightRangeReply, other.GetBlocksByHeightRangeReply)) return false;
      if (!object.Equals(GetTransactionsByHashesRequest, other.GetTransactionsByHashesRequest)) return false;
      if (!object.Equals(GetTransactionsByHashesReply, other.GetTransactionsByHashesReply)) return false;
      if (!object.Equals(ThresholdRequest, other.ThresholdRequest)) return false;
      if (!object.Equals(ConsensusMessage, other.ConsensusMessage)) return false;
      if (!object.Equals(Signature, other.Signature)) return false;
      if (MessageCase != other.MessageCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Magic != 0) hash ^= Magic.GetHashCode();
      if (messageCase_ == MessageOneofCase.HandshakeRequest) hash ^= HandshakeRequest.GetHashCode();
      if (messageCase_ == MessageOneofCase.HandshakeReply) hash ^= HandshakeReply.GetHashCode();
      if (messageCase_ == MessageOneofCase.PingRequest) hash ^= PingRequest.GetHashCode();
      if (messageCase_ == MessageOneofCase.PingReply) hash ^= PingReply.GetHashCode();
      if (messageCase_ == MessageOneofCase.GetBlocksByHashesRequest) hash ^= GetBlocksByHashesRequest.GetHashCode();
      if (messageCase_ == MessageOneofCase.GetBlocksByHashesReply) hash ^= GetBlocksByHashesReply.GetHashCode();
      if (messageCase_ == MessageOneofCase.GetBlocksByHeightRangeRequest) hash ^= GetBlocksByHeightRangeRequest.GetHashCode();
      if (messageCase_ == MessageOneofCase.GetBlocksByHeightRangeReply) hash ^= GetBlocksByHeightRangeReply.GetHashCode();
      if (messageCase_ == MessageOneofCase.GetTransactionsByHashesRequest) hash ^= GetTransactionsByHashesRequest.GetHashCode();
      if (messageCase_ == MessageOneofCase.GetTransactionsByHashesReply) hash ^= GetTransactionsByHashesReply.GetHashCode();
      if (messageCase_ == MessageOneofCase.ThresholdRequest) hash ^= ThresholdRequest.GetHashCode();
      if (messageCase_ == MessageOneofCase.ConsensusMessage) hash ^= ConsensusMessage.GetHashCode();
      if (signature_ != null) hash ^= Signature.GetHashCode();
      hash ^= (int) messageCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Magic != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Magic);
      }
      if (messageCase_ == MessageOneofCase.HandshakeRequest) {
        output.WriteRawTag(82);
        output.WriteMessage(HandshakeRequest);
      }
      if (messageCase_ == MessageOneofCase.HandshakeReply) {
        output.WriteRawTag(90);
        output.WriteMessage(HandshakeReply);
      }
      if (messageCase_ == MessageOneofCase.PingRequest) {
        output.WriteRawTag(98);
        output.WriteMessage(PingRequest);
      }
      if (messageCase_ == MessageOneofCase.PingReply) {
        output.WriteRawTag(106);
        output.WriteMessage(PingReply);
      }
      if (messageCase_ == MessageOneofCase.GetBlocksByHashesRequest) {
        output.WriteRawTag(114);
        output.WriteMessage(GetBlocksByHashesRequest);
      }
      if (messageCase_ == MessageOneofCase.GetBlocksByHashesReply) {
        output.WriteRawTag(122);
        output.WriteMessage(GetBlocksByHashesReply);
      }
      if (messageCase_ == MessageOneofCase.GetBlocksByHeightRangeRequest) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(GetBlocksByHeightRangeRequest);
      }
      if (messageCase_ == MessageOneofCase.GetBlocksByHeightRangeReply) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(GetBlocksByHeightRangeReply);
      }
      if (messageCase_ == MessageOneofCase.GetTransactionsByHashesRequest) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(GetTransactionsByHashesRequest);
      }
      if (messageCase_ == MessageOneofCase.GetTransactionsByHashesReply) {
        output.WriteRawTag(154, 1);
        output.WriteMessage(GetTransactionsByHashesReply);
      }
      if (messageCase_ == MessageOneofCase.ThresholdRequest) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(ThresholdRequest);
      }
      if (messageCase_ == MessageOneofCase.ConsensusMessage) {
        output.WriteRawTag(170, 1);
        output.WriteMessage(ConsensusMessage);
      }
      if (signature_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(Signature);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Magic != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Magic);
      }
      if (messageCase_ == MessageOneofCase.HandshakeRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HandshakeRequest);
      }
      if (messageCase_ == MessageOneofCase.HandshakeReply) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HandshakeReply);
      }
      if (messageCase_ == MessageOneofCase.PingRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PingRequest);
      }
      if (messageCase_ == MessageOneofCase.PingReply) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PingReply);
      }
      if (messageCase_ == MessageOneofCase.GetBlocksByHashesRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetBlocksByHashesRequest);
      }
      if (messageCase_ == MessageOneofCase.GetBlocksByHashesReply) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetBlocksByHashesReply);
      }
      if (messageCase_ == MessageOneofCase.GetBlocksByHeightRangeRequest) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(GetBlocksByHeightRangeRequest);
      }
      if (messageCase_ == MessageOneofCase.GetBlocksByHeightRangeReply) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(GetBlocksByHeightRangeReply);
      }
      if (messageCase_ == MessageOneofCase.GetTransactionsByHashesRequest) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(GetTransactionsByHashesRequest);
      }
      if (messageCase_ == MessageOneofCase.GetTransactionsByHashesReply) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(GetTransactionsByHashesReply);
      }
      if (messageCase_ == MessageOneofCase.ThresholdRequest) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ThresholdRequest);
      }
      if (messageCase_ == MessageOneofCase.ConsensusMessage) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ConsensusMessage);
      }
      if (signature_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Signature);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NetworkMessage other) {
      if (other == null) {
        return;
      }
      if (other.Magic != 0) {
        Magic = other.Magic;
      }
      if (other.signature_ != null) {
        if (signature_ == null) {
          signature_ = new global::Phorkus.Proto.Signature();
        }
        Signature.MergeFrom(other.Signature);
      }
      switch (other.MessageCase) {
        case MessageOneofCase.HandshakeRequest:
          if (HandshakeRequest == null) {
            HandshakeRequest = new global::Phorkus.Proto.HandshakeRequest();
          }
          HandshakeRequest.MergeFrom(other.HandshakeRequest);
          break;
        case MessageOneofCase.HandshakeReply:
          if (HandshakeReply == null) {
            HandshakeReply = new global::Phorkus.Proto.HandshakeReply();
          }
          HandshakeReply.MergeFrom(other.HandshakeReply);
          break;
        case MessageOneofCase.PingRequest:
          if (PingRequest == null) {
            PingRequest = new global::Phorkus.Proto.PingRequest();
          }
          PingRequest.MergeFrom(other.PingRequest);
          break;
        case MessageOneofCase.PingReply:
          if (PingReply == null) {
            PingReply = new global::Phorkus.Proto.PingReply();
          }
          PingReply.MergeFrom(other.PingReply);
          break;
        case MessageOneofCase.GetBlocksByHashesRequest:
          if (GetBlocksByHashesRequest == null) {
            GetBlocksByHashesRequest = new global::Phorkus.Proto.GetBlocksByHashesRequest();
          }
          GetBlocksByHashesRequest.MergeFrom(other.GetBlocksByHashesRequest);
          break;
        case MessageOneofCase.GetBlocksByHashesReply:
          if (GetBlocksByHashesReply == null) {
            GetBlocksByHashesReply = new global::Phorkus.Proto.GetBlocksByHashesReply();
          }
          GetBlocksByHashesReply.MergeFrom(other.GetBlocksByHashesReply);
          break;
        case MessageOneofCase.GetBlocksByHeightRangeRequest:
          if (GetBlocksByHeightRangeRequest == null) {
            GetBlocksByHeightRangeRequest = new global::Phorkus.Proto.GetBlocksByHeightRangeRequest();
          }
          GetBlocksByHeightRangeRequest.MergeFrom(other.GetBlocksByHeightRangeRequest);
          break;
        case MessageOneofCase.GetBlocksByHeightRangeReply:
          if (GetBlocksByHeightRangeReply == null) {
            GetBlocksByHeightRangeReply = new global::Phorkus.Proto.GetBlocksByHeightRangeReply();
          }
          GetBlocksByHeightRangeReply.MergeFrom(other.GetBlocksByHeightRangeReply);
          break;
        case MessageOneofCase.GetTransactionsByHashesRequest:
          if (GetTransactionsByHashesRequest == null) {
            GetTransactionsByHashesRequest = new global::Phorkus.Proto.GetTransactionsByHashesRequest();
          }
          GetTransactionsByHashesRequest.MergeFrom(other.GetTransactionsByHashesRequest);
          break;
        case MessageOneofCase.GetTransactionsByHashesReply:
          if (GetTransactionsByHashesReply == null) {
            GetTransactionsByHashesReply = new global::Phorkus.Proto.GetTransactionsByHashesReply();
          }
          GetTransactionsByHashesReply.MergeFrom(other.GetTransactionsByHashesReply);
          break;
        case MessageOneofCase.ThresholdRequest:
          if (ThresholdRequest == null) {
            ThresholdRequest = new global::Phorkus.Proto.ThresholdRequest();
          }
          ThresholdRequest.MergeFrom(other.ThresholdRequest);
          break;
        case MessageOneofCase.ConsensusMessage:
          if (ConsensusMessage == null) {
            ConsensusMessage = new global::Phorkus.Proto.ConsensusMessage();
          }
          ConsensusMessage.MergeFrom(other.ConsensusMessage);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Magic = input.ReadUInt32();
            break;
          }
          case 82: {
            global::Phorkus.Proto.HandshakeRequest subBuilder = new global::Phorkus.Proto.HandshakeRequest();
            if (messageCase_ == MessageOneofCase.HandshakeRequest) {
              subBuilder.MergeFrom(HandshakeRequest);
            }
            input.ReadMessage(subBuilder);
            HandshakeRequest = subBuilder;
            break;
          }
          case 90: {
            global::Phorkus.Proto.HandshakeReply subBuilder = new global::Phorkus.Proto.HandshakeReply();
            if (messageCase_ == MessageOneofCase.HandshakeReply) {
              subBuilder.MergeFrom(HandshakeReply);
            }
            input.ReadMessage(subBuilder);
            HandshakeReply = subBuilder;
            break;
          }
          case 98: {
            global::Phorkus.Proto.PingRequest subBuilder = new global::Phorkus.Proto.PingRequest();
            if (messageCase_ == MessageOneofCase.PingRequest) {
              subBuilder.MergeFrom(PingRequest);
            }
            input.ReadMessage(subBuilder);
            PingRequest = subBuilder;
            break;
          }
          case 106: {
            global::Phorkus.Proto.PingReply subBuilder = new global::Phorkus.Proto.PingReply();
            if (messageCase_ == MessageOneofCase.PingReply) {
              subBuilder.MergeFrom(PingReply);
            }
            input.ReadMessage(subBuilder);
            PingReply = subBuilder;
            break;
          }
          case 114: {
            global::Phorkus.Proto.GetBlocksByHashesRequest subBuilder = new global::Phorkus.Proto.GetBlocksByHashesRequest();
            if (messageCase_ == MessageOneofCase.GetBlocksByHashesRequest) {
              subBuilder.MergeFrom(GetBlocksByHashesRequest);
            }
            input.ReadMessage(subBuilder);
            GetBlocksByHashesRequest = subBuilder;
            break;
          }
          case 122: {
            global::Phorkus.Proto.GetBlocksByHashesReply subBuilder = new global::Phorkus.Proto.GetBlocksByHashesReply();
            if (messageCase_ == MessageOneofCase.GetBlocksByHashesReply) {
              subBuilder.MergeFrom(GetBlocksByHashesReply);
            }
            input.ReadMessage(subBuilder);
            GetBlocksByHashesReply = subBuilder;
            break;
          }
          case 130: {
            global::Phorkus.Proto.GetBlocksByHeightRangeRequest subBuilder = new global::Phorkus.Proto.GetBlocksByHeightRangeRequest();
            if (messageCase_ == MessageOneofCase.GetBlocksByHeightRangeRequest) {
              subBuilder.MergeFrom(GetBlocksByHeightRangeRequest);
            }
            input.ReadMessage(subBuilder);
            GetBlocksByHeightRangeRequest = subBuilder;
            break;
          }
          case 138: {
            global::Phorkus.Proto.GetBlocksByHeightRangeReply subBuilder = new global::Phorkus.Proto.GetBlocksByHeightRangeReply();
            if (messageCase_ == MessageOneofCase.GetBlocksByHeightRangeReply) {
              subBuilder.MergeFrom(GetBlocksByHeightRangeReply);
            }
            input.ReadMessage(subBuilder);
            GetBlocksByHeightRangeReply = subBuilder;
            break;
          }
          case 146: {
            global::Phorkus.Proto.GetTransactionsByHashesRequest subBuilder = new global::Phorkus.Proto.GetTransactionsByHashesRequest();
            if (messageCase_ == MessageOneofCase.GetTransactionsByHashesRequest) {
              subBuilder.MergeFrom(GetTransactionsByHashesRequest);
            }
            input.ReadMessage(subBuilder);
            GetTransactionsByHashesRequest = subBuilder;
            break;
          }
          case 154: {
            global::Phorkus.Proto.GetTransactionsByHashesReply subBuilder = new global::Phorkus.Proto.GetTransactionsByHashesReply();
            if (messageCase_ == MessageOneofCase.GetTransactionsByHashesReply) {
              subBuilder.MergeFrom(GetTransactionsByHashesReply);
            }
            input.ReadMessage(subBuilder);
            GetTransactionsByHashesReply = subBuilder;
            break;
          }
          case 162: {
            global::Phorkus.Proto.ThresholdRequest subBuilder = new global::Phorkus.Proto.ThresholdRequest();
            if (messageCase_ == MessageOneofCase.ThresholdRequest) {
              subBuilder.MergeFrom(ThresholdRequest);
            }
            input.ReadMessage(subBuilder);
            ThresholdRequest = subBuilder;
            break;
          }
          case 170: {
            global::Phorkus.Proto.ConsensusMessage subBuilder = new global::Phorkus.Proto.ConsensusMessage();
            if (messageCase_ == MessageOneofCase.ConsensusMessage) {
              subBuilder.MergeFrom(ConsensusMessage);
            }
            input.ReadMessage(subBuilder);
            ConsensusMessage = subBuilder;
            break;
          }
          case 802: {
            if (signature_ == null) {
              signature_ = new global::Phorkus.Proto.Signature();
            }
            input.ReadMessage(signature_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
