language: csharp
mono: none
dist: xenial
addons:
  snaps:
    - name: dotnet-sdk
      confinement: classic
      channel: 5.0/beta
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
install:
  - export PATH="$PATH:/home/travis/.dotnet/tools"
  - export PATH="$PATH:$HOME/.local/bin"
  - sudo snap alias dotnet-sdk.dotnet dotnet

script:
  - dotnet restore
  - dotnet build -c Release
  #- dotnet test
  - dotnet publish -p:Configuration=Release -p:PublishTrimmed=true -p:SelfContained=true -p:PublishSingleFile=true --runtime linux-x64 src/Lachain.Console/Lachain.Console.csproj
  - dotnet publish -p:Configuration=Release -p:PublishTrimmed=true -p:SelfContained=true -p:PublishSingleFile=true --runtime win-x64 src/Lachain.Console/Lachain.Console.csproj
  - dotnet publish -p:Configuration=Release -p:PublishTrimmed=true -p:SelfContained=true -p:PublishSingleFile=true --runtime osx-x64 src/Lachain.Console/Lachain.Console.csproj
  - mkdir build
  - cp src/Lachain.Console/bin/Release/netcoreapp3.1/linux-x64/publish/Lachain.Console build/lachain-linux-x64
  - cp src/Lachain.Console/bin/Release/netcoreapp3.1/osx-x64/publish/Lachain.Console build/lachain-osx-x64
  - cp src/Lachain.Console/bin/Release/netcoreapp3.1/win-x64/publish/Lachain.Console.exe build/lachain-win-x64.exe

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: build/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
