language: csharp
mono: none
dist: bionic
dotnet: 3.1
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
install:
  - dotnet restore

script:
  - dotnet build -c Release
  - dotnet test test/Lachain.CryptoTest
  - dotnet test test/Lachain.ConsensusTest
  - dotnet test test/Lachain.CoreTest
  - dotnet publish -p:Configuration=Release -p:PublishTrimmed=true -p:SelfContained=true -p:PublishSingleFile=true --runtime linux-x64 src/Lachain.Console/Lachain.Console.csproj
  - dotnet publish -p:Configuration=Release -p:PublishTrimmed=true -p:SelfContained=true -p:PublishSingleFile=true --runtime win-x64 src/Lachain.Console/Lachain.Console.csproj
  - dotnet publish -p:Configuration=Release -p:PublishTrimmed=true -p:SelfContained=true -p:PublishSingleFile=true --runtime osx-x64 src/Lachain.Console/Lachain.Console.csproj
  - mkdir build
  - cp src/Lachain.Console/bin/Release/netcoreapp3.1/linux-x64/publish/Lachain.Console build/lachain-linux-x64
  - cp src/Lachain.Console/bin/Release/netcoreapp3.1/osx-x64/publish/Lachain.Console build/lachain-osx-x64
  - cp src/Lachain.Console/bin/Release/netcoreapp3.1/win-x64/publish/Lachain.Console.exe build/lachain-win-x64.exe

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: build/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
