version: '2.4'
services:
  node0:
    build:
      network: host
      context: ./
      args:
        CONFIG: src/Lachain.Console/config0.json
        WALLET: src/Lachain.Console/wallet0.json
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
    - "5051:5051"
    network_mode: "host"

  node1:
    build:
      network: host
      context: ./
      args:
        CONFIG: src/Lachain.Console/config1.json
        WALLET: src/Lachain.Console/wallet1.json
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
    - "5052:5052"
    network_mode: "host"

  node2:
    build:
      context: ./
      network: host
      args:
        CONFIG: src/Lachain.Console/config2.json
        WALLET: src/Lachain.Console/wallet2.json
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
    - "5053:5053"
    network_mode: "host"

  node3:
    build:
      context: ./
      network: host
      args:
        CONFIG: src/Lachain.Console/config3.json
        WALLET: src/Lachain.Console/wallet3.json
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
    - "5054:5054"
    network_mode: "host"
