version: '2.4'
services:
  node0:
    build:
      context: ./
      args:
        CONFIG: src/Phorkus.Console/config0.json
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
    - "5051:5051"
    network_mode: "host"

  node1:
    build:
      context: ./
      args:
        CONFIG: src/Phorkus.Console/config1.json
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
    - "5052:5052"
    network_mode: "host"

  node2:
    build:
      context: ./
      args:
        CONFIG: src/Phorkus.Console/config2.json
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
    - "5053:5053"
    network_mode: "host"

  node3:
    build:
      context: ./
      args:
        CONFIG: src/Phorkus.Console/config3.json
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
    - "5054:5054"
    network_mode: "host"
