version: '2.4'
services:
  node0:
    build:
      network: host
      context: ./
      args:
        CONFIG: config.json
      dockerfile: Dockerfile
    stdin_open: true
    environment:
      - LOG_LEVEL=Trace
    tty: true
    network_mode: "host"
    restart: always
