// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: blockchain_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Phorkus.Network.Grpc {

  /// <summary>Holder for reflection information generated from blockchain_service.proto</summary>
  public static partial class BlockchainServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for blockchain_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BlockchainServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhibG9ja2NoYWluX3NlcnZpY2UucHJvdG8aDW1lc3NhZ2UucHJvdG8y4wMK",
            "EUJsb2NrY2hhaW5TZXJ2aWNlEi8KCUhhbmRzaGFrZRIRLkhhbmRzaGFrZVJl",
            "cXVlc3QaDy5IYW5kc2hha2VSZXBseRIgCgRQaW5nEgwuUGluZ1JlcXVlc3Qa",
            "Ci5QaW5nUmVwbHkSSQoRR2V0QmxvY2tzQnlIYXNoZXMSGS5HZXRCbG9ja3NC",
            "eUhhc2hlc1JlcXVlc3QaFy5HZXRCbG9ja3NCeUhhc2hlc1JlcGx5MAESWAoW",
            "R2V0QmxvY2tzQnlIZWlnaHRSYW5nZRIeLkdldEJsb2Nrc0J5SGVpZ2h0UmFu",
            "Z2VSZXF1ZXN0GhwuR2V0QmxvY2tzQnlIZWlnaHRSYW5nZVJlcGx5MAESWwoX",
            "R2V0VHJhbnNhY3Rpb25zQnlIYXNoZXMSHy5HZXRUcmFuc2FjdGlvbnNCeUhh",
            "c2hlc1JlcXVlc3QaHS5HZXRUcmFuc2FjdGlvbnNCeUhhc2hlc1JlcGx5MAES",
            "eQohR2V0VHJhbnNhY3Rpb25IYXNoZXNCeUJsb2NrSGVpZ2h0EikuR2V0VHJh",
            "bnNhY3Rpb25IYXNoZXNCeUJsb2NrSGVpZ2h0UmVxdWVzdBonLkdldFRyYW5z",
            "YWN0aW9uSGFzaGVzQnlCbG9ja0hlaWdodFJlcGx5MAFCF6oCFFBob3JrdXMu",
            "TmV0d29yay5HcnBjYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Phorkus.Proto.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
