// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: threshold_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Phorkus.Network.Grpc {
  public static partial class ThresholdService
  {
    static readonly string __ServiceName = "ThresholdService";

    static readonly grpc::Marshaller<global::Phorkus.Network.Grpc.ThresholdMessage> __Marshaller_ThresholdMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Phorkus.Network.Grpc.ThresholdMessage.Parser.ParseFrom);

    static readonly grpc::Method<global::Phorkus.Network.Grpc.ThresholdMessage, global::Phorkus.Network.Grpc.ThresholdMessage> __Method_ExchangeMessage = new grpc::Method<global::Phorkus.Network.Grpc.ThresholdMessage, global::Phorkus.Network.Grpc.ThresholdMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ExchangeMessage",
        __Marshaller_ThresholdMessage,
        __Marshaller_ThresholdMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Phorkus.Network.Grpc.ThresholdServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ThresholdService</summary>
    public abstract partial class ThresholdServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Phorkus.Network.Grpc.ThresholdMessage> ExchangeMessage(global::Phorkus.Network.Grpc.ThresholdMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ThresholdService</summary>
    public partial class ThresholdServiceClient : grpc::ClientBase<ThresholdServiceClient>
    {
      /// <summary>Creates a new client for ThresholdService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ThresholdServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ThresholdService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ThresholdServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ThresholdServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ThresholdServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Phorkus.Network.Grpc.ThresholdMessage ExchangeMessage(global::Phorkus.Network.Grpc.ThresholdMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExchangeMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Phorkus.Network.Grpc.ThresholdMessage ExchangeMessage(global::Phorkus.Network.Grpc.ThresholdMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ExchangeMessage, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Phorkus.Network.Grpc.ThresholdMessage> ExchangeMessageAsync(global::Phorkus.Network.Grpc.ThresholdMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExchangeMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Phorkus.Network.Grpc.ThresholdMessage> ExchangeMessageAsync(global::Phorkus.Network.Grpc.ThresholdMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ExchangeMessage, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ThresholdServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ThresholdServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ThresholdServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ExchangeMessage, serviceImpl.ExchangeMessage).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ThresholdServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ExchangeMessage, serviceImpl.ExchangeMessage);
    }

  }
}
#endregion
