// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: blockchain_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Phorkus.Rpc {
  public static partial class BlockchainService
  {
    static readonly string __ServiceName = "BlockchainService";

    static readonly grpc::Marshaller<global::Phorkus.Rpc.GetBlockByHeightRequest> __Marshaller_GetBlockByHeightRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Phorkus.Rpc.GetBlockByHeightRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Phorkus.Rpc.GetBlockByHeightReply> __Marshaller_GetBlockByHeightReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Phorkus.Rpc.GetBlockByHeightReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Phorkus.Rpc.GetBlockByHeightRequest, global::Phorkus.Rpc.GetBlockByHeightReply> __Method_GetBlockByHeight = new grpc::Method<global::Phorkus.Rpc.GetBlockByHeightRequest, global::Phorkus.Rpc.GetBlockByHeightReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetBlockByHeight",
        __Marshaller_GetBlockByHeightRequest,
        __Marshaller_GetBlockByHeightReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Phorkus.Rpc.BlockchainServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of BlockchainService</summary>
    public abstract partial class BlockchainServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Phorkus.Rpc.GetBlockByHeightReply> GetBlockByHeight(global::Phorkus.Rpc.GetBlockByHeightRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for BlockchainService</summary>
    public partial class BlockchainServiceClient : grpc::ClientBase<BlockchainServiceClient>
    {
      /// <summary>Creates a new client for BlockchainService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public BlockchainServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for BlockchainService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public BlockchainServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected BlockchainServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected BlockchainServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Phorkus.Rpc.GetBlockByHeightReply GetBlockByHeight(global::Phorkus.Rpc.GetBlockByHeightRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetBlockByHeight(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Phorkus.Rpc.GetBlockByHeightReply GetBlockByHeight(global::Phorkus.Rpc.GetBlockByHeightRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetBlockByHeight, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Phorkus.Rpc.GetBlockByHeightReply> GetBlockByHeightAsync(global::Phorkus.Rpc.GetBlockByHeightRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetBlockByHeightAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Phorkus.Rpc.GetBlockByHeightReply> GetBlockByHeightAsync(global::Phorkus.Rpc.GetBlockByHeightRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetBlockByHeight, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override BlockchainServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BlockchainServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(BlockchainServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetBlockByHeight, serviceImpl.GetBlockByHeight).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, BlockchainServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetBlockByHeight, serviceImpl.GetBlockByHeight);
    }

  }
}
#endregion
