namespace Lachain.Core.Blockchain.Error
{
    public enum OperatingError : byte
    {
        Ok,
        HashMismatched,
        InvalidNonce,
        UnsupportedTransaction,
        InvalidSignature,
        InvalidTransaction,
        AlreadyExists,
        PrevBlockHashMismatched,
        InvalidBlock,
        QuorumNotReached,
        InvalidStateHash,
        TransactionLost,
        InvalidMultisig,
        BlockAlreadyExists,
        InvalidMerkeRoot,
        ContractFailed,
        ContractNotFound,
        InvalidContract,
        OutOfGas,
        InvalidGasLimit,
        InsufficientBalance,
        InvalidInput,
        BlockGasOverflow,
        Underpriced,
        ValueOverflow,
    }
}