name: Deploy Testnet
on:
  workflow_dispatch:
  push:
    tags:
      - v*-stable

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: rlespinasse/github-slug-action@v4
    - name: Rancher Deploy
      uses: LATOKEN/actions-rancher-update@1.1.5
      with:
        rancher_url: ${{ secrets.TEST_RANCHER_URL_API }}
        rancher_access: ${{ secrets.TEST_RANCHER_ACCESS_KEY}}
        rancher_key: ${{ secrets.TEST_RANCHER_SECRET_KEY }}
        project_id: 1a41
        stack_name: lachain-testnet
        service_name: lachain
        docker_image: ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}:${{ env.GITHUB_REF_SLUG_URL }}
        retry: 90
        timeout: 1
    - name: Send release message to slack chat
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "text": "New release lachain:${{ github.ref_name }} deployed to Testnet by ${{ github.actor }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "New release lachain:${{ github.ref_name }} deployed to Testnet by ${{ github.actor }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.TEST_RELAYERS_SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
